### PR TITLE
Fix URLs in .gitmodules

### PR DESCRIPTION
**Pull request by tkysk**
change protocol from 'git' to 'https'

Signed-off-by: Takuya Saeki <t@example.com>

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
Hi @tkysk 

PR looks good! Have you had a chance to sign the CLA?

Cheers,
Amit

**Comment by tkysk** [comment]
Hi Amit

I have just signed and sent CLA.

Tanks,

**Comment by Amit-PivotalLabs** [comment]
@cfdreddbot hasn't picked it up yet, but I checked with the Cloud Foundry Foundation and they've processed it (next PR it should automatically detect that you've signed it).

Will prioritize this for the team to merge.

**Comment by zankich** [comment]
@tkysk Thanks for the PR! Would you mind changing the target from the `master` branch to `develop`?

**Comment by tkysk** [comment]
@zankich I have re-submitted the PR. Please look #13.

**Pull request closed without merging**
