### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by mhoran**
This adds support for running consul-release on Windows. Note that we've still got a WIP commit and other cleanup to do, but we wanted to get this in front of the infrastructure team ASAP to get their thoughts.

We need to run confab in the foreground as the Windows job monitor does not support daemonized processes.

We also needed to change `isProcessRunning` to be platform-independent.

### CODE REVIEW

**Comment by Amit-PivotalLabs** [comment]
Thanks @mhoran 

Let's discuss this in more detail.  We'd like to understand the priority of Windows support in the broader CF roadmap context.  I assume it's high (@dieucao?), in which case we would want to make sure we're treating consul on windows as a first-class thing, and developing it in the right way (e.g. perhaps we should be building consul from source so that we don't need two consul binaries).  A big thing we'll want to figure out is CI, how should we run unit tests and bosh-deploy tests in a Windows context?

/cc @zankich @kkallday @gdean123 @christianang 

Amit

**Comment by dieucao** [comment]
@Amit-PivotalLabs Yes, we want consul on windows to work. Not sure how much is involved with doing it the right way, but strictly speaking from what I've heard from the community and customers, consul support for Elastic Clusters (consul-wan epic) is higher priority.

**Comment by benmoss** [comment]
For unit tests we have had success using https://github.com/concourse/bin, you can look at https://github.com/cloudfoundry/bosh-agent/blob/master/ci/tasks/test-unit-windows.yml or https://github.com/concourse/concourse/blob/master/ci/fly-windows.yml for examples of how this can be done. As long as you're just building/running Go it shouldn't be terribly difficult.

We can definitely look into adding coverage of the Windows job to the acceptance tests, probably some cross-team pairing would be the best approach there. Compiling Consul from source is also something we'd be happy to join in exploring, we are already compiling confab so hopefully there won't be too much complexity than we already had to solve there.

**Comment by Amit-PivotalLabs** [comment]
Thanks for starting this discussion @mhoran 

We think it's a significant effort to support Windows correctly, and set up CI for this.  We definitely want to do this, but it is not imminent on our roadmap.  We should incept on this track of work at a later date, for now I will close this PR. /cc @luan

**Comment by luan** [comment]
I captured some more work that would need to be done for this to work here: https://www.pivotaltracker.com/story/show/119393251, for convenience:

Per investigation on #118834249 we found that the way `confab` manages the consul process by deferring the writing of the pidfile until the cluster is detected as healthy. This behavior is not supported on windows because the only check that is done by bosh-windows is wether the process is running or not.

This causes the deployment to succeed to early, before `confab` has a chance to write the pidfile or make any decisions, bosh-windows also does not look at pidfiles at all.

Per Dmitriy's recommendation we should not be relying too much of specific monit behaviors like this one, the fact that `confab` has an implicit dependency on that is not desirable by bosh standards. A way to fix that would be to use a [post start script](http://bosh.io/docs/post-start.html) to do the health check after the process is started, post-start scripts add some more flexibility that could we could take advantage of to make things like this work on bosh-windows.

@Amit-PivotalLabs @benmoss @mhoran

**Comment by Amit-PivotalLabs** [comment]
Thanks @luan 

Just want to copy a comment from our Slack conversation:

> We rely on people being able to manually recover a cluster from a disaster scenario by doing stuff and then running `monit start`

**Pull request closed without merging**
